// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftXmlToExcel.Data;

#nullable disable

namespace SwiftXmlToExcel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwiftXmlToExcel.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BICFI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("C_Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("C_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("I_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("R_Info_Unstructured")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ref_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Settlement_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
