<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CBS.Domain\CBS.Domain.csproj" />
    <ProjectReference Include="..\CBS.Application\CBS.Application.csproj" />
    <ProjectReference Include="..\CBS.Infrastructure\CBS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
